# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
## 网站标题
title: Hogan'Blog
subtitle: ''
## 网站描述
description: Talk is not cheap. Talk can be powerful.
keywords:
## 作者
author: Hogan Lee
## 语言：简体中文
language: zh-Hans
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://forhcl.github.io
## 网站根目录
root: /
## 文章的永久链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
## 文章资源文件夹
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## 启用Next主题
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:forhcl/forhcl.github.io.git
  branch: master

# hexo-hide-posts
hide_posts:
  # 可以改成其他你喜欢的名字
  filter: hidden
  # 指定你想要传递隐藏文章的 generator，比如让所有隐藏文章在存档页面可见
  # 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  public_generators: []
  # 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: true

# hexo-generator-searchdb
search:
  path: search.xml
  field: post
  content: true
  format: html

# hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-chitose
  display:
    position: left
    width: 200
    height: 400
  mobile:
    show: true
  react:
    opacity: 0.7

# hexo-tag-plantuml
tag_plantuml:
	type: static

# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

theme_config:
  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------

  # To get or check favicons visit: https://realfavicongenerator.net
  # Put your favicons into `hexo-site/source/` (recommend) or `hexo-site/themes/next/source/images/` directory.

  # Default NexT favicons placed in `hexo-site/themes/next/source/images/` directory.
  # And if you want to place your icons in `hexo-site/source/` root directory, you must remove `/images` prefix from pathes.

  # For example, you put your favicons into `hexo-site/source/images` directory.
  # Then need to rename & redefine they on any other names, otherwise icons from Next will rewrite your custom icons in Hexo.
  favicon:
    #small: /images/favicon-16x16-next.png
    medium: /images/Favicon.png
    #apple_touch_icon: /images/apple-touch-icon-next.png
    #safari_pinned_tab: /images/logo.svg
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml
  # ---------------------------------------------------------------
  # Sidebar Settings
  # ---------------------------------------------------------------

  # Social Links.
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
  social:
    GitHub: https://github.com/forhcl || github
    E-Mail: mailto:18028543308@163.com || envelope
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #VK Group: https://vk.com/yourname || vk
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype

  social_icons:
    enable: true
    icons_only: false
    transition: false

  # Blog rolls
  links_icon: link
  links_title: Links
  links_layout: block
  #links_layout: inline
  #links:
    #Title: http://example.com/


  # Sidebar Avatar
  # in theme directory(source/images): /images/avatar.gif
  # in site  directory(source/uploads): /uploads/avatar.gif
  avatar: /images/avatar.jpg

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  #scheme: Muse
  scheme: Mist
  #scheme: Pisces
  #scheme: Gemini

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If translate for this menu will find in languages - this translate will be loaded; if not - Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  menu:
    home: /||home
    #about: /about||user
    tags: /tags||tags
    categories: /categories||th
    archives: /archives||archive
    #schedule: /schedule||calendar
    #sitemap: /sitemap.xml||sitemap
    #commonweal: /404||heartbeat

  # Enable/Disable menu icons.
  menu_icons:
    enable: true
  
  # Local search
  # Dependencies: https://github.com/flashlab/hexo-generator-search
  local_search:
    enable: true
    # if auto, trigger search by changing input
    # if manual, trigger search by pressing enter key or search button
    trigger: auto
    # show top n results per article, show all results by setting to -1
    top_n_per_article: 1
  
  footer:
    # Specify the date when the site was setup.
    # If not defined, current year will be used.
    since: 2018

    # Icon between year and copyright info.
    icon: user

    # If not defined, will be used `author` from Hexo main config.
    copyright:
    # -------------------------------------------------------------
    # Hexo link (Powered by Hexo).
    powered: true

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: true
      # Version info of NexT after scheme info (vX.X.X).
      version: true
    # -------------------------------------------------------------
    # Any custom text can be defined here.
    #custom_text: Hosted by <a target="_blank" href="https://pages.github.com">GitHub Pages</a>

    # ---------------------------------------------------------------
  # Third Party Services Settings
  # ---------------------------------------------------------------

  # MathJax Support
  mathjax:
    enable: true
    per_page: false
    cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
  
  # Declare license on posts
  post_copyright:
    enable: true
    license: CC BY-NC-SA 3.0
    license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/
  # 文章结束标记
  passage_end_tag:
  # 是否显示文章结束标记
    enable: true